name: "Rust Android"

on:
  push:
    branches: [ master, instancing_rework ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ master, instancing_rework ]
    tags:
      - 'v*.*.*'

env:
  CARGO_TERM_COLOR: always
  CARGO_TARGET_DIR: ./crates/target

jobs:
  check:
    name: "Android Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: "Install stable toolchain"
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: aarch64-linux-android
          components: clippy

      - name: "Update repos"
        run: |
          cd crates
          cargo update
          cd ..

      - name: "Install cargo-ndk"
        run: cargo install cargo-ndk

      - name: "Run cargo clippy check"
        run: |
          cd crates
          cargo ndk -t arm64-v8a clippy --release --no-deps -- -D warnings

      - name: "Run cargo test inox_core"
        run: |
          cd crates
          cargo test -p inox_core

      - name: "Run cargo build release"
        run: |
          cd crates
          cargo ndk -t arm64-v8a build --release
